jenkins:
    service:
        image: komljen/jenkins
        name: jenkins
        port: "8080"
    images:
        - ubuntu
        - jdk-oracle
        - jenkins

redis:
    service:
        image: komljen/redis
        name: redis
        port: "6379"
    images:
        - ubuntu
        - redis

abh-jmeter:
    images:
        - ubuntu
        - jdk-oracle
        - maven
        - jmeter-abh
